In [3]:
import numpy as np
import torch

In [4]:
# NumPy 1D Array
np_1d = np.array([1.0, 2.0, 3.0])

# PyTorch 1D Tensor
pt_1d = torch.tensor([1.0, 2.0, 3.0])

In [5]:
# NumPy 2D Array (2 rows, 3 columns)
np_2d = np.array([[1, 2, 3], 
                  [4, 5, 6]])

# PyTorch 2D Tensor
pt_2d = torch.tensor([[1, 2, 3], 
                      [4, 5, 6]])

In [6]:
# NumPy 3D Array (Shape: 2x2x2)
np_3d = np.array([[[1, 2], [3, 4]], 
                  [[5, 6], [7, 8]]])

# PyTorch 3D Tensor (Shape: 2x2x2)
pt_3d = torch.tensor([[[1, 2], [3, 4]], 
                      [[5, 6], [7, 8]]])

In [12]:

# Define inputs
A = torch.tensor([[1, 2], [3, 4]])
B = torch.tensor([[5, 6], [7, 8]])

print("--- Element-wise Operations ---")
print(f"Addition (A + B):\n{A + B}\n")
print(f"Subtraction (A - B):\n{A - B}\n")
print(f"Multiplication (A * B):\n{A * B}\n")
print(f"Division (A / B):\n{A / B}\n")

--- Element-wise Operations ---
Addition (A + B):
tensor([[ 6,  8],
        [10, 12]])

Subtraction (A - B):
tensor([[-4, -4],
        [-4, -4]])

Multiplication (A * B):
tensor([[ 5, 12],
        [21, 32]])

Division (A / B):
tensor([[0.2000, 0.3333],
        [0.4286, 0.5000]])



In [14]:
# Dot product using row wise multiplication & adding them up
dot_product = torch.sum(A*B, dim=1)
print(f"Dot Product of {A} and {B}: {dot_product}")

Dot Product of tensor([[1, 2],
        [3, 4]]) and tensor([[5, 6],
        [7, 8]]): tensor([17, 53])


In [15]:
# Matrix Multiplication using the @ operator
mat_mul = A @ B

print("--- Matrix Multiplication (A @ B) ---")
print(mat_mul)

--- Matrix Multiplication (A @ B) ---
tensor([[19, 22],
        [43, 50]])


In [17]:
# Slicing 
# Create a 4x4 Tensor
data = torch.tensor([[10, 20, 30, 40],
                     [50, 60, 70, 80],
                     [90, 100, 110, 120],
                     [130, 140, 150, 160]])

# 1. Extract a single row (Index 1)
row = data[1, :]      # Output: tensor([50, 60, 70, 80])

# 2. Extract a single column (Index 2)
col = data[:, 2]      # Output: tensor([30, 70, 110, 150])

# 3. Extract a 2x2 Sub-matrix (Top-right corner)
sub_tensor = data[0:2, 2:4]
print(sub_tensor)

tensor([[30, 40],
        [70, 80]])


In [22]:
# Boolean Masking
x = torch.tensor([1, 5, 10, 15, 20])

# Create a boolean mask (True where value > 10)
mask = x > 10 
# Output of mask: tensor([False, False, False,  True,  True])

# Apply the mask to extract values
filtered_data = x[mask]
print("\nBoolean Mask (x > 10):")
print(mask)

print("\nFiltered Data (Values where mask is True):")
print(filtered_data)


Boolean Mask (x > 10):
tensor([False, False, False,  True,  True])

Filtered Data (Values where mask is True):
tensor([15, 20])


In [21]:
#Conditional Replacement
# Create a 3x3 matrix
matrix = torch.randn(3, 3) # Random numbers

# Replace all negative numbers with 0 (Commonly known as ReLU in AI)
matrix[matrix < 0] = 0

print(matrix)

tensor([[0.0000, 0.6580, 1.5931],
        [0.0000, 0.0000, 0.0000],
        [0.0000, 1.7430, 0.0000]])


In [23]:
# Create a 1D tensor with 6 elements
pt_tensor = torch.tensor([1, 2, 3, 4, 5, 6])

# Change to 2x3 matrix
view_tensor = pt_tensor.view(2, 3)
reshape_tensor = pt_tensor.reshape(2, 3)

print("Original:\n", pt_tensor)
print("Reshaped (2x3):\n", reshape_tensor)

Original:
 tensor([1, 2, 3, 4, 5, 6])
Reshaped (2x3):
 tensor([[1, 2, 3],
        [4, 5, 6]])


In [24]:
# Create a 2D tensor (Shape: 2, 3)
x = torch.zeros(2, 3) 

# Add a dimension at index 0 (Shape: 1, 2, 3)
# Common for adding a 'Batch' dimension
unsqueezed = x.unsqueeze(0) 

# Remove the dimension (Shape: 2, 3)
squeezed = unsqueezed.squeeze(0)

print(f"Original shape: {x.shape}")
print(f"After unsqueeze(0): {unsqueezed.shape}")
print(f"After squeeze(0): {squeezed.shape}")

Original shape: torch.Size([2, 3])
After unsqueeze(0): torch.Size([1, 2, 3])
After squeeze(0): torch.Size([2, 3])


In [25]:
#Adding a Scalar to a Matrix
# Shape (2, 2)
A = torch.tensor([[10, 20], 
                  [30, 40]])

# Shape (1) - This will be "broadcast" to match A
result = A + 5 

print("Broadcasted Addition:\n", result)
# Output: [[15, 25], [35, 45]]

Broadcasted Addition:
 tensor([[15, 25],
        [35, 45]])


In [26]:
#Adding a Row Vector to a Matrix
# Shape (2, 3)
matrix = torch.ones(2, 3)
# Shape (3) -> becomes (1, 3) -> stretched to (2, 3)
row_vector = torch.tensor([1, 2, 3])

combined = matrix + row_vector
print("\nMatrix + Row Vector:\n", combined)
# Output: [[2, 3, 4], [2, 3, 4]]


Matrix + Row Vector:
 tensor([[2., 3., 4.],
        [2., 3., 4.]])


In [27]:
x = torch.tensor([1.0, 2.0])

# Out-of-place
y = x.add(5)
print(f"Out-of-place: x is {x}, y is {y}") 

# In-place
x.add_(5) 
print(f"In-place: x is {x}") 

Out-of-place: x is tensor([1., 2.]), y is tensor([6., 7.])
In-place: x is tensor([6., 7.])
